### PR TITLE
This is an "invite only" channel.

### PR DESCRIPTION
**Pull request by megacoder**
Please review membership settings for this chat room.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Instead of removing the channel details, could you rather fix it to reference the real official channel, i.e. `#oracle-linux` on Freenode?

**Comment by megacoder** [comment]
I have run across the #oraclelinux channel more than once on customer-facing pages and never once have I seen '#oracle-linux' so least-effort suggests we decide which one to bless.

**Comment by Djelibeybi** [comment]
The official channel on Freenode is `#oracle-linux` because Oracle now owns the entire `#oracle-` namespace on Freenode. Anything else must be removed or changed.

**Comment by megacoder** [comment]
OK, on the customer-facing cloud pages (I'll get the URL's tomorrow) we'll
need to figure out whom to contact to make the corrections there.

Every web page should have a contact-the-author link in case of errors like
this.  PDIT strikes again 8-) 😎

**Comment by megacoder** [comment]
OK, I changed #oraclelinux to #oracle-linux and also changed to https:// URL schemes throughout.

**Pull request merged**
